version: '3.3'

services:
  freescout-app:
    image: tiredofit/freescout
    container_name: freescout-demo
    deploy:
      mode: replicated
      placement:  # use for deploy all the containers on manager node instead of worker nodes
        constraints:
          - node.role == manager
      replicas: 1 # number of nodes
    networks:
      - elb
    # ports:
    # - 80:80
    # links:
    # - freescout-db
    volumes:
    ### If you want to perform customizations to the source and have access to it, then uncomment this line - This includes modules
    #- ./data:/www/html
    ### Or, if you just want to use Stock Freescout and hold onto persistent files like cache and session use this, one or the other.
    - pv:/data
    ### If you want to just keep the original source and add additional modules uncomment this line
    #- ./modules:/www/html/Modules
    - pv:/www/logs
    environment:
    - CONTAINER_NAME=freescout-demo
    
    - DB_HOST=prod-2.rds.cloudgate.lk
    - DB_NAME=freescout_demo
    - DB_USER=freescout_demo
    - DB_PASS=afJVGN!cxb1C

    - SITE_URL=https://fc.ceylonmicroservices.cloud
    - ADMIN_EMAIL=support@ceylonmicroservices.cloud
    - ADMIN_PASS=freescout
    - ENABLE_SSL_PROXY=TRUE
    - DISPLAY_ERRORS=FALSE
    - TIMEZONE=Asia/Colombo
    restart: always

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.freescout-demo.entrypoints=web, websecure"
      - "traefik.http.routers.freescout-demo.rule=Host(`fc.ceylonmicroservices.cloud`)"
      - "traefik.http.routers.freescout-demo.tls=true"
      - "traefik.http.routers.freescout-demo.tls.certresolver=production"
      - "traefik.http.routers.freescout-demo.service=freescout-demo_service"
      - "traefik.http.services.freescout-demo_service.loadbalancer.server.port=80"

  # freescout-db:
  #   image: tiredofit/mariadb
  #   container_name: freescout-db
  #   volumes:
  #     - ./db:/var/lib/mysql
  #   environment:
  #     - ROOT_PASS=password
  #     - DB_NAME=freescout
  #     - DB_USER=freescout
  #     - DB_PASS=freescout

  #     - CONTAINER_NAME=freescout-db
  #   restart: always

  # freescout-db-backup:
  #   container_name: freescout-db-backup
  #   image: tiredofit/db-backup
  #   links:
  #    - freescout-db
  #   volumes:
  #     - ./dbbackup:/backup
  #   environment:
  #     - CONTAINER_NAME=freescout-db-backup
  #     - DB_HOST=freescout-db
  #     - DB_TYPE=mariadb
  #     - DB_NAME=freescout
  #     - DB_USER=freescout
  #     - DB_PASS=freescout
  #     - DB_DUMP_FREQ=1440
  #     - DB_DUMP_BEGIN=0000
  #     - DB_CLEANUP_TIME=8640
  #     - COMPRESSION=BZ
  #     - MD5=TRUE
  #   restart: always
volumes:
    pv:
        external: false
     
networks:
  elb:
    external:
      name: elb