version: '3.3'
services:
  freescout-app:
    image: tiredofit/freescout
    container_name: freescout-demo
    deploy:
      mode: replicated
      placement:  # use for deploy all the containers on manager node instead of worker nodes
        constraints:
          - node.role == manager
      replicas: 1 # number of nodes
    networks:
      - elb
    volumes:
    ### If you want to perform customizations to the source and have access to it, then uncomment this line - This includes modules
    #- ./data:/www/html
    ### Or, if you just want to use Stock Freescout and hold onto persistent files like cache and session use this, one or the other.
    - pv:/data
    ### If you want to just keep the original source and add additional modules uncomment this line
    #- ./modules:/www/html/Modules
    - pv:/www/logs
    environment:
    - CONTAINER_NAME=freescout-demo
    
    - DB_HOST=DB_CREDENTIALS
    - DB_NAME=DB_CREDENTIALS
    - DB_USER=DB_CREDENTIALS
    - DB_PASS=DB_CREDENTIALS

    - SITE_URL=SITE_URL
    - ADMIN_EMAIL=ADMIN_EMAIL
    - ADMIN_PASS=YOURPASS
    - ENABLE_SSL_PROXY=TRUE
    - DISPLAY_ERRORS=FALSE
    - TIMEZONE=Asia/Colombo
    restart: always

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.freescout-demo.entrypoints=web, websecure"
      - "traefik.http.routers.freescout-demo.rule=Host(`DOMAIN`)"
      - "traefik.http.routers.freescout-demo.tls=true"
      - "traefik.http.routers.freescout-demo.tls.certresolver=production"
      - "traefik.http.routers.freescout-demo.service=freescout-demo_service"
      - "traefik.http.services.freescout-demo_service.loadbalancer.server.port=80"

volumes:
    pv:
        external: false
     
networks:
  elb:
    external:
      name: elb