---
version: "3.3"
services:
  librespeed:
    image: lscr.io/linuxserver/librespeed:latest
    deploy:
      mode: replicated
      placement:  # use for deploy all the containers on manager node instead of worker nodes
        constraints:
          - node.role == manager
      replicas: 1 # number of nodes
    networks:
      - elb
    container_name: librespeed
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Colombo
      - PASSWORD=PASSWORD
      - CUSTOM_RESULTS=false #optional
      # - DB_TYPE=sqlite #optional
      - DB_NAME=DB_CREDENTIALS #optional
      - DB_HOSTNAME=DB_CREDENTIALS #optional
      - DB_USERNAME=DB_CREDENTIALS #optional
      - DB_PASSWORD=DB_CREDENTIALS #optional
      - DB_PORT=3306 #optional

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.NEW_LABEL.entrypoints=web, websecure"
      - "traefik.http.routers.NEW_LABEL.rule=Host(`speedtest.cloudgate.lk`)"
      - "traefik.http.routers.NEW_LABEL.tls=true"
      - "traefik.http.routers.NEW_LABEL.tls.certresolver=production"
      - "traefik.http.routers.NEW_LABEL.service=NEW_LABEL"
      - "traefik.http.services.NEW_LABEL.loadbalancer.server.port=80"
    volumes:
      - pv:/config
    
    restart: unless-stopped
volumes:
    pv:
        external: false
networks:
  elb:
    external:
      name: elb