version: '3.3'

services:
  nginx-php-fpm-app:
    image: tiredofit/nginx-php-fpm:debian-7.4-buster-latest
    deploy:
      mode: replicated
      placement:  # use for deploy all the containers on manager node instead of worker nodes
        constraints:
          - node.role == manager
      replicas: 1 # number of nodes
    networks:
      - elb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.NEW_LABEL.entrypoints=web, websecure"
      - "traefik.http.routers.NEW_LABEL.rule=Host(`DOMAIN_NAME`)"
      - "traefik.http.routers.NEW_LABEL.tls=true"
      - "traefik.http.routers.NEW_LABEL.tls.certresolver=production"
      - "traefik.http.routers.NEW_LABEL.service=NEW_SERVICE"
      - "traefik.http.services.NEW_SERVICE.loadbalancer.server.port=80"
    volumes:
      - pv:/www/html
      - pv:/www/logs
    environment:
      - TIMEZONE=Asia/Colombo

    restart: always

volumes:
    pv:
        external: false

networks:
  elb:
    external:
      name: elb
