version: '3'

volumes:
 traefik-ssl-certs:
  driver: local

services:
  traefik:
    image: "traefik:v2.8.2"
    container_name: "traefik"
    networks:
      - elb
    ports:
      - "80:80"
      - "443:443"
      # (Optional) Expose Dashboard
      - "8080:8080"  # Don't do this in production!
    restart: always

    labels:
      - "providers.docker.endpoint=tcp://IP_ADDRESS:2377"
      - "providers.docker.swarmMode=true"
    volumes:
      - /etc/traefik:/etc/traefik
#      - traefik-ssl-certs:/etc/traefik/ssl-certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
networks:
  elb:
    external:
      name: elb

