version: '3.3'
services:   
   wordpress:
     image: serverhublk/wordpress-nginx-php8.0:latest
     deploy:
      mode: replicated
      placement:  # use for deploy all the containers on manager node instead of worker nodes
        constraints:
          - node.role == manager
      replicas: 1 # number of nodes
     networks:
      - elb
     restart: always
     environment:
      DB_HOST: DB_CREDENTIALS
      DB_PASSWORD: DB_CREDENTIALS
      DB_NAME: DB_CREDENTIALS
      DB_USER: DB_CREDENTIALS
      WORDPRESS_SITE_URL: http://localhost
      FS_METHOD: direct
       
     labels:
      - "traefik.enable=true"
      - "traefik.http.routers.NEW_LABEL.entrypoints=web, websecure"
      - "traefik.http.routers.NEW_LABEL.rule=Host(`DOMAIN_NAME`)"
      - "traefik.http.routers.NEW_LABEL.tls=true"
      - "traefik.http.routers.NEW_LABEL.tls.certresolver=production"
      - "traefik.http.routers.NEW_LABEL.service=NEW_SERVICE"
      - "traefik.http.services.NEW_SERVICE.loadbalancer.server.port=80"
    

     volumes:
      - pv:/var/www/wp-content # wordpress Content as persistant volume

volumes:
    pv:
        external: false
     
networks:
  elb:
    external:
      name: elb